# Build a Docker image based on Alpine Linux version 3.19
FROM alpine:3.19

# https://hub.docker.com/r/grafana/grafana
# Utiliser l'image officielle de Grafana
FROM grafana/grafana:8.3.3

# Exposer le port pour Grafana
EXPOSE 3000
