# Generated by Django 5.0.1 on 2024-01-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_tournament_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='leaderboard',
            field=models.JSONField(default=list),
        ),
    ]
