# Generated by Django 5.0.1 on 2024-01-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_tournament_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='players_count',
            field=models.PositiveSmallIntegerField(choices=[(4, 4), (8, 8)], default=8),
        ),
    ]
