# Generated by Django 5.0.1 on 2024-02-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_user_photo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='photo_url',
            new_name='photo_medium_url',
        ),
        migrations.AddField(
            model_name='user',
            name='photo_small_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
