# Generated by Django 5.0.1 on 2024-02-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_customuser_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_42_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
