# Generated by Django 5.0.1 on 2024-02-15 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_42_authenticated',
        ),
    ]
