# Generated by Django 5.0.1 on 2024-02-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_customuser_is_42_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_dev',
            field=models.BooleanField(default=False),
        ),
    ]
