# Generated by Django 5.0.1 on 2024-02-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_squashed_0015_customuser_is_dev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_dev',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='join_date',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
