# Generated by Django 5.0.1 on 2024-02-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_remove_customuser_is_dev_remove_customuser_join_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='campus',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
