# Generated by Django 5.0.1 on 2024-02-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='github',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
