# Generated by Django 5.0.1 on 2024-02-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_customuser_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image_path',
            field=models.CharField(blank=True, default='default_profile_image.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='uploaded_image',
            field=models.CharField(blank=True, default='default_profile_image.jpg', max_length=255),
        ),
    ]
