# Generated by Django 5.0.1 on 2024-02-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_customuser_nickname_customuser_profile_image_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='uploaded_image',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
