# Generated by Django 5.0.1 on 2024-02-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_customuser_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
