# Generated by Django 5.0.1 on 2024-02-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_remove_tournament_host_customuser_tournaments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='usernames',
            field=models.JSONField(default=list),
        ),
    ]
