# Generated by Django 5.0.1 on 2024-02-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_leaderboard_usernames'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='games',
            field=models.ManyToManyField(related_name='players', to='backend.game'),
        ),
    ]
