# Generated by Django 5.0.1 on 2024-02-20 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_customuser_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='stats',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='backend.stats'),
            preserve_default=False,
        ),
    ]
