# Generated by Django 5.0.1 on 2024-02-20 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_remove_stats_user_customuser_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stats',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='backend.stats'),
        ),
    ]
