# Generated by Django 5.0.1 on 2024-02-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_alter_customuser_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='players', to='backend.game'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tournaments',
            field=models.ManyToManyField(blank=True, related_name='players', to='backend.tournament'),
        ),
    ]
