# Generated by Django 5.0.1 on 2024-02-20 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_alter_customuser_games_alter_customuser_tournaments'),
    ]

    operations = [
    ]
