# Generated by Django 5.0.1 on 2024-02-20 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_merge_20240219_1559'),
        ('backend', '0029_merge_20240220_0242'),
    ]

    operations = [
    ]
