# Generated by Django 5.0.1 on 2024-02-21 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_merge_20240220_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='backend.tournament'),
        ),
    ]
