# Generated by Django 5.0.1 on 2024-02-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_game_tournament'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
