# Generated by Django 5.0.1 on 2024-02-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_delete_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
