# Utiliser l'image officielle de Prometheus
FROM prom/prometheus:v2.30.3

# Copier votre fichier de configuration Prometheus si nécessaire
# COPY prometheus.yml /etc/prometheus/

# Exposer le port pour Prometheus
EXPOSE 9090
